
    resource "checkpoint_management_group" "user" {
        name = "gr_user"
        members = ["ra_user_gustavojohnselq4f","ra_user_tanyawisozkqkb91","ra_user_wilmaemardilv3jy","ra_user_glendabahrindq9rn","ra_user_lisafraneckihbzba","ra_user_jacquelinehugesxm","ra_user_horacedeckowabq4a","ra_user_mrscharleneh33lno","ra_user_cedrickossr7ups","ra_user_tinawyman4xw9u","ra_user_drmyronrusseziq85","ra_user_sadieortizb2eoc","ra_user_arlenecummerkgy7r","ra_user_andyjacobshvvjf","ra_user_garretthintz64lgw","ra_user_eloiseankundwcp4s","ra_user_mrsharrietemrrdxn","ra_user_joshuaschowa4z3h9","ra_user_dorishalvorsxy9te","ra_user_lyledachqgzch","ra_user_caseynitzsch4flcs","ra_user_candicekemmec0fsb","ra_user_edmondsporeru1634","ra_user_williamhomen2s0m4","ra_user_stewartkreig9wgpy","ra_user_christyfaheyhq74g","ra_user_roxannealtenr3tia","ra_user_msmargaritakxb5y3","ra_user_abrahammurazdrr5a","ra_user_staceycollinhwlo9","ra_user_anthonylarsoodpmc","ra_user_patryannclzr","ra_user_mrkellyrayno7uhxa","ra_user_franknicolasczbz2"]

        depends_on = [ checkpoint_management_host.gustavojohnselq4f, checkpoint_management_host.tanyawisozkqkb91, checkpoint_management_host.wilmaemardilv3jy, checkpoint_management_host.glendabahrindq9rn, checkpoint_management_host.lisafraneckihbzba, checkpoint_management_host.jacquelinehugesxm, checkpoint_management_host.horacedeckowabq4a, checkpoint_management_host.mrscharleneh33lno, checkpoint_management_host.cedrickossr7ups, checkpoint_management_host.tinawyman4xw9u, checkpoint_management_host.drmyronrusseziq85, checkpoint_management_host.sadieortizb2eoc, checkpoint_management_host.arlenecummerkgy7r, checkpoint_management_host.andyjacobshvvjf, checkpoint_management_host.garretthintz64lgw, checkpoint_management_host.eloiseankundwcp4s, checkpoint_management_host.mrsharrietemrrdxn, checkpoint_management_host.joshuaschowa4z3h9, checkpoint_management_host.dorishalvorsxy9te, checkpoint_management_host.lyledachqgzch, checkpoint_management_host.caseynitzsch4flcs, checkpoint_management_host.candicekemmec0fsb, checkpoint_management_host.edmondsporeru1634, checkpoint_management_host.williamhomen2s0m4, checkpoint_management_host.stewartkreig9wgpy, checkpoint_management_host.christyfaheyhq74g, checkpoint_management_host.roxannealtenr3tia, checkpoint_management_host.msmargaritakxb5y3, checkpoint_management_host.abrahammurazdrr5a, checkpoint_management_host.staceycollinhwlo9, checkpoint_management_host.anthonylarsoodpmc, checkpoint_management_host.patryannclzr, checkpoint_management_host.mrkellyrayno7uhxa, checkpoint_management_host.franknicolasczbz2 ]
    }
    

    resource "checkpoint_management_group" "audit" {
        name = "gr_audit"
        members = ["ra_user_scottcorkery7vum1","ra_user_judithwolf2sw0s","ra_user_jamiecollinse2vj1","ra_user_marcocummingy4gyj","ra_user_francismcdera7xha","ra_user_delbertwalshwwaun","ra_user_cedriclynch57cvk","ra_user_madelinehaleoja6t","ra_user_lorraineprica93vq","ra_user_mspennygoldn7eg88","ra_user_emmagusikowsxxocb","ra_user_mrpablolynch6l6tb","ra_user_doreenstromanhww6","ra_user_mikeyostds4ny","ra_user_tinastoltenbewy4s","ra_user_marilynpredopq2db","ra_user_juanaskilesjf1vi","ra_user_charliehesseh95hw","ra_user_melindaschae0q8i2","ra_user_irvingortizsp1mrh","ra_user_angelfeeneybarqs","ra_user_haroldortiz86yln","ra_user_missanitahillhexn","ra_user_dalelarkinisi5p","ra_user_margaretjonea38qv","ra_user_mrmariondareijep1","ra_user_geraldweiman9ast5","ra_user_misstamarafeh08ri","ra_user_terikerluke60t6d"]

        depends_on = [ checkpoint_management_host.scottcorkery7vum1, checkpoint_management_host.judithwolf2sw0s, checkpoint_management_host.jamiecollinse2vj1, checkpoint_management_host.marcocummingy4gyj, checkpoint_management_host.francismcdera7xha, checkpoint_management_host.delbertwalshwwaun, checkpoint_management_host.cedriclynch57cvk, checkpoint_management_host.madelinehaleoja6t, checkpoint_management_host.lorraineprica93vq, checkpoint_management_host.mspennygoldn7eg88, checkpoint_management_host.emmagusikowsxxocb, checkpoint_management_host.mrpablolynch6l6tb, checkpoint_management_host.doreenstromanhww6, checkpoint_management_host.mikeyostds4ny, checkpoint_management_host.tinastoltenbewy4s, checkpoint_management_host.marilynpredopq2db, checkpoint_management_host.juanaskilesjf1vi, checkpoint_management_host.charliehesseh95hw, checkpoint_management_host.melindaschae0q8i2, checkpoint_management_host.irvingortizsp1mrh, checkpoint_management_host.angelfeeneybarqs, checkpoint_management_host.haroldortiz86yln, checkpoint_management_host.missanitahillhexn, checkpoint_management_host.dalelarkinisi5p, checkpoint_management_host.margaretjonea38qv, checkpoint_management_host.mrmariondareijep1, checkpoint_management_host.geraldweiman9ast5, checkpoint_management_host.misstamarafeh08ri, checkpoint_management_host.terikerluke60t6d ]
    }
    

    resource "checkpoint_management_group" "admin" {
        name = "gr_admin"
        members = ["ra_user_brendanullri7v74i","ra_user_rufuslabadiel7103","ra_user_dwaynegreenhlfszu","ra_user_altonhellerq3ii8","ra_user_andrewgislassgakn","ra_user_robinkshleridkkyd","ra_user_lyndacolei1zgr","ra_user_rachellangdv3zfv9","ra_user_melissapadbet6pje","ra_user_kathleenwillpx7tx","ra_user_gerardohermir1uo0","ra_user_terryhellercbm1v","ra_user_tombashiriansdj6e","ra_user_jonathonkirlfdac5","ra_user_anneuptonyza71","ra_user_blakehomenica43sl","ra_user_msmarthalittz3sjx","ra_user_ismaelbrakusfz2xx","ra_user_katherinedubbs6ui","ra_user_kimwalterid0ky","ra_user_dominicstammwgb52","ra_user_ericschmidtvi5eog","ra_user_moniquekrisihg6r","ra_user_mshollynolan3gz8l","ra_user_christinahahvhyaw","ra_user_camillegislahva19","ra_user_kyleondricka4lq0z","ra_user_tamaraterry6u9un","ra_user_sheilaleanno0c471","ra_user_gingerweberda1xpx","ra_user_hazelbauch8ip1l","ra_user_hermanharberp11mp","ra_user_ellenjacobso484az","ra_user_kathrynokonbxyuk","ra_user_staceybogankd9xp","ra_user_martahessel45454","ra_user_mrsstellaullyg5y9"]

        depends_on = [ checkpoint_management_host.brendanullri7v74i, checkpoint_management_host.rufuslabadiel7103, checkpoint_management_host.dwaynegreenhlfszu, checkpoint_management_host.altonhellerq3ii8, checkpoint_management_host.andrewgislassgakn, checkpoint_management_host.robinkshleridkkyd, checkpoint_management_host.lyndacolei1zgr, checkpoint_management_host.rachellangdv3zfv9, checkpoint_management_host.melissapadbet6pje, checkpoint_management_host.kathleenwillpx7tx, checkpoint_management_host.gerardohermir1uo0, checkpoint_management_host.terryhellercbm1v, checkpoint_management_host.tombashiriansdj6e, checkpoint_management_host.jonathonkirlfdac5, checkpoint_management_host.anneuptonyza71, checkpoint_management_host.blakehomenica43sl, checkpoint_management_host.msmarthalittz3sjx, checkpoint_management_host.ismaelbrakusfz2xx, checkpoint_management_host.katherinedubbs6ui, checkpoint_management_host.kimwalterid0ky, checkpoint_management_host.dominicstammwgb52, checkpoint_management_host.ericschmidtvi5eog, checkpoint_management_host.moniquekrisihg6r, checkpoint_management_host.mshollynolan3gz8l, checkpoint_management_host.christinahahvhyaw, checkpoint_management_host.camillegislahva19, checkpoint_management_host.kyleondricka4lq0z, checkpoint_management_host.tamaraterry6u9un, checkpoint_management_host.sheilaleanno0c471, checkpoint_management_host.gingerweberda1xpx, checkpoint_management_host.hazelbauch8ip1l, checkpoint_management_host.hermanharberp11mp, checkpoint_management_host.ellenjacobso484az, checkpoint_management_host.kathrynokonbxyuk, checkpoint_management_host.staceybogankd9xp, checkpoint_management_host.martahessel45454, checkpoint_management_host.mrsstellaullyg5y9 ]
    }
    
