
    resource "checkpoint_management_group" "admin" {
        name = "gr_admin"
        members = ["ra_user_paulinewilli3jwms","ra_user_rooseveltdic5fzyb","ra_user_drtheodorehe0mawo","ra_user_kirkgoyettes7ofh9","ra_user_drgeneviever25dr3","ra_user_guysauerdvmh7lsa","ra_user_marjorieadama3q41","ra_user_ramirorobelq8ud0","ra_user_ericastarkltipb","ra_user_edwinvandervtb31o","ra_user_mrshannonbea9binj","ra_user_georgiahamilxrtnx","ra_user_kellilowe4s9ef","ra_user_rosemariehanca7d0","ra_user_juanitaabbotxgmz3","ra_user_ryanyundtgtqay","ra_user_ramonajohnsoricj9","ra_user_darylondrickpoxvj","ra_user_felipeokeefeobgoe","ra_user_darrelwilder3dlvb","ra_user_maryannmetz8jckx","ra_user_violetrunolfoe0fy","ra_user_hughritchieojpnm","ra_user_dorajohnstonkze9n","ra_user_tobyaueru61r9","ra_user_perrycummeramgm2b","ra_user_altonauerze3qt","ra_user_lelamillervmyrj","ra_user_jerryhowel4w8x","ra_user_angelmarvin45uh9","ra_user_judykris96o7m","ra_user_loreneframix19ix","ra_user_franceshicklky8g4","ra_user_devinmurphypwk04","ra_user_delbertaufdeisp7o","ra_user_saraschneide4xjh3","ra_user_deborahcolejsf07n"]

        depends_on = [ checkpoint_management_host.paulinewilli3jwms, checkpoint_management_host.rooseveltdic5fzyb, checkpoint_management_host.drtheodorehe0mawo, checkpoint_management_host.kirkgoyettes7ofh9, checkpoint_management_host.drgeneviever25dr3, checkpoint_management_host.guysauerdvmh7lsa, checkpoint_management_host.marjorieadama3q41, checkpoint_management_host.ramirorobelq8ud0, checkpoint_management_host.ericastarkltipb, checkpoint_management_host.edwinvandervtb31o, checkpoint_management_host.mrshannonbea9binj, checkpoint_management_host.georgiahamilxrtnx, checkpoint_management_host.kellilowe4s9ef, checkpoint_management_host.rosemariehanca7d0, checkpoint_management_host.juanitaabbotxgmz3, checkpoint_management_host.ryanyundtgtqay, checkpoint_management_host.ramonajohnsoricj9, checkpoint_management_host.darylondrickpoxvj, checkpoint_management_host.felipeokeefeobgoe, checkpoint_management_host.darrelwilder3dlvb, checkpoint_management_host.maryannmetz8jckx, checkpoint_management_host.violetrunolfoe0fy, checkpoint_management_host.hughritchieojpnm, checkpoint_management_host.dorajohnstonkze9n, checkpoint_management_host.tobyaueru61r9, checkpoint_management_host.perrycummeramgm2b, checkpoint_management_host.altonauerze3qt, checkpoint_management_host.lelamillervmyrj, checkpoint_management_host.jerryhowel4w8x, checkpoint_management_host.angelmarvin45uh9, checkpoint_management_host.judykris96o7m, checkpoint_management_host.loreneframix19ix, checkpoint_management_host.franceshicklky8g4, checkpoint_management_host.devinmurphypwk04, checkpoint_management_host.delbertaufdeisp7o, checkpoint_management_host.saraschneide4xjh3, checkpoint_management_host.deborahcolejsf07n ]
    }
    

    resource "checkpoint_management_group" "user" {
        name = "gr_user"
        members = ["ra_user_cliftonankun3nh6o","ra_user_saulhageneso2trq","ra_user_eduardozbonc4a6yp","ra_user_ismaeldaughe0y4wf","ra_user_kaylanaderrqx10","ra_user_darinkassulkrho21","ra_user_jackgradyh4x8c","ra_user_missdanazbon2o91i","ra_user_drbrianmills19b3h","ra_user_gaylefayx99p1","ra_user_mrivanstarkhy0h8","ra_user_mrrooseveltr9l6ss","ra_user_debbiestracknz7vr","ra_user_erikwintheissa1gr","ra_user_alvinmosciskzubux","ra_user_lorenamuller8e8er","ra_user_franciscoankpu5wn","ra_user_hermanbayer642r9","ra_user_jesusflatleyqvemv","ra_user_maxinenaderjul8t","ra_user_catherineschcl15s","ra_user_toddosinskibxk8w","ra_user_naomihansenk9y6s","ra_user_robertobeer81nm7","ra_user_oliverframikxulka"]

        depends_on = [ checkpoint_management_host.cliftonankun3nh6o, checkpoint_management_host.saulhageneso2trq, checkpoint_management_host.eduardozbonc4a6yp, checkpoint_management_host.ismaeldaughe0y4wf, checkpoint_management_host.kaylanaderrqx10, checkpoint_management_host.darinkassulkrho21, checkpoint_management_host.jackgradyh4x8c, checkpoint_management_host.missdanazbon2o91i, checkpoint_management_host.drbrianmills19b3h, checkpoint_management_host.gaylefayx99p1, checkpoint_management_host.mrivanstarkhy0h8, checkpoint_management_host.mrrooseveltr9l6ss, checkpoint_management_host.debbiestracknz7vr, checkpoint_management_host.erikwintheissa1gr, checkpoint_management_host.alvinmosciskzubux, checkpoint_management_host.lorenamuller8e8er, checkpoint_management_host.franciscoankpu5wn, checkpoint_management_host.hermanbayer642r9, checkpoint_management_host.jesusflatleyqvemv, checkpoint_management_host.maxinenaderjul8t, checkpoint_management_host.catherineschcl15s, checkpoint_management_host.toddosinskibxk8w, checkpoint_management_host.naomihansenk9y6s, checkpoint_management_host.robertobeer81nm7, checkpoint_management_host.oliverframikxulka ]
    }
    

    resource "checkpoint_management_group" "audit" {
        name = "gr_audit"
        members = ["ra_user_douglaslangzzdrv","ra_user_bethkossidmp3","ra_user_drdawngottli3aaw6","ra_user_spencerboehm5jpe3","ra_user_stevebergstrlsj2h","ra_user_paulettewill6h4zv","ra_user_marshallkass9tpnr","ra_user_gingerskilesru5jm","ra_user_miriamhoegerc0dmp","ra_user_naomiwizaxmrwa","ra_user_lauriebednarja9ip","ra_user_terrymaggiops9fnc","ra_user_johnhilllk89ce","ra_user_martaconnellwzrq8","ra_user_mrsjenniefar1gxp1","ra_user_adrianhillstcvir","ra_user_allanglover4wdsm","ra_user_patricialaki4goro","ra_user_wallacehodki0h2v8","ra_user_rosemarytranv5psv","ra_user_kirksauerwnvx2","ra_user_hopeswaniawsnavr7","ra_user_brentsimonis4b2eq","ra_user_drjorgewilki500vz","ra_user_rickeyfeilcv5kk","ra_user_randolphking6ybjm","ra_user_morrismacgyv3twvw","ra_user_catherinerod5j2k3","ra_user_donnakozeyh67nl","ra_user_drcarypollicfe2vq","ra_user_drsidneyluetrvwgh","ra_user_cristinaernswb8tn","ra_user_timmyreicherkx8n5","ra_user_nicolelebsacijrda","ra_user_joanncollieryrxxr","ra_user_byronyundt7ma4d","ra_user_drtashahicklond6c","ra_user_simonschinneaa5ri"]

        depends_on = [ checkpoint_management_host.douglaslangzzdrv, checkpoint_management_host.bethkossidmp3, checkpoint_management_host.drdawngottli3aaw6, checkpoint_management_host.spencerboehm5jpe3, checkpoint_management_host.stevebergstrlsj2h, checkpoint_management_host.paulettewill6h4zv, checkpoint_management_host.marshallkass9tpnr, checkpoint_management_host.gingerskilesru5jm, checkpoint_management_host.miriamhoegerc0dmp, checkpoint_management_host.naomiwizaxmrwa, checkpoint_management_host.lauriebednarja9ip, checkpoint_management_host.terrymaggiops9fnc, checkpoint_management_host.johnhilllk89ce, checkpoint_management_host.martaconnellwzrq8, checkpoint_management_host.mrsjenniefar1gxp1, checkpoint_management_host.adrianhillstcvir, checkpoint_management_host.allanglover4wdsm, checkpoint_management_host.patricialaki4goro, checkpoint_management_host.wallacehodki0h2v8, checkpoint_management_host.rosemarytranv5psv, checkpoint_management_host.kirksauerwnvx2, checkpoint_management_host.hopeswaniawsnavr7, checkpoint_management_host.brentsimonis4b2eq, checkpoint_management_host.drjorgewilki500vz, checkpoint_management_host.rickeyfeilcv5kk, checkpoint_management_host.randolphking6ybjm, checkpoint_management_host.morrismacgyv3twvw, checkpoint_management_host.catherinerod5j2k3, checkpoint_management_host.donnakozeyh67nl, checkpoint_management_host.drcarypollicfe2vq, checkpoint_management_host.drsidneyluetrvwgh, checkpoint_management_host.cristinaernswb8tn, checkpoint_management_host.timmyreicherkx8n5, checkpoint_management_host.nicolelebsacijrda, checkpoint_management_host.joanncollieryrxxr, checkpoint_management_host.byronyundt7ma4d, checkpoint_management_host.drtashahicklond6c, checkpoint_management_host.simonschinneaa5ri ]
    }
    
